name: Frontend Build and Deploy

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install
      
      - name: Build frontend
        run: npm run build:prod
      
      - name: Trigger test workflow
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.TRIGGER }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'ChampionKFC',
              repo: 'devops-gravitino',
              workflow_id: 'test_workflow.yml',
              ref: 'main',
              inputs: {
                // Define inputs if any
              }
            });
            

